version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api1:
    build: .
    hostname: api1
    env_file: .env
    depends_on:
      - db
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    build: .
    hostname: api2
    env_file: .env
    depends_on:
      - db
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
    image: postgres:14
    container_name: rinha_db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  pgadmin:
    image: dpage/pgadmin4
    container_name: rinha_pg
    env_file: .env
    ports:
      - 8888:80