version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api1:
    build: .
    hostname: api1
    env_file: .env
    depends_on:
      - db
      - redis
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    build: .
    hostname: api2
    env_file: .env
    depends_on:
      - db
      - redis
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
    image: postgres:14
    container_name: rinha_db
    env_file: .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1GB'
  redis: 
    image: redis
    expose:
      - 6379
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'